context: '/scratch/gpfs/SIMONSOBS/users/erosenberg/contexts/use_this_local_satp1.yaml'
site: so_sat1
nside: 512
query: 'obslist_satp1_debug.txt'
odir: 'debug/atomics'
atomic_db: 'atomics.db'
preprocess_config: 'minimal_preprocess.yaml'
dtype_map: 'float32'
freq: "f150"
wafer: "ws0"